package com.doms.doms.serviceImpl;
import com.doms.doms.dto.*; import com.doms.doms.entity.*; import com.doms.doms.exception.ResourceNotFoundException; import com.doms.doms.repository.*; import com.doms.doms.service.DocumentShareService;
import lombok.RequiredArgsConstructor; import org.springframework.security.core.context.SecurityContextHolder; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.LocalDateTime; import java.util.*;
@Service @RequiredArgsConstructor @Transactional
public class DocumentShareServiceImpl implements DocumentShareService {
 private final DocumentShareRepository shares; private final DocumentRepository documents; private final UserRepository users;private final com.doms.doms.service.AuditService audit;
 public List<ShareResponse> share(Long id,ShareRequest r){User sender=current();Document d=documents.findByUploadedByAndId(sender,id).orElseThrow(()->new ResourceNotFoundException("Only the document owner can share it"));List<ShareResponse> out=new ArrayList<>();for(Long uid:r.userIds()){User receiver=users.findById(uid).orElseThrow(()->new ResourceNotFoundException("User not found: "+uid));if(receiver.getRole()==Role.ROLE_ADMIN)throw new IllegalArgumentException("System administrators cannot be selected for document sharing");if(receiver.getId().equals(sender.getId()))throw new IllegalArgumentException("A document cannot be shared with its owner");DocumentShare s=shares.findByDocumentAndSharedTo(d,receiver).orElseGet(()->DocumentShare.builder().document(d).sharedBy(sender).sharedTo(receiver).build());s.setPermission(SharePermission.DOWNLOAD);s.setSharedAt(LocalDateTime.now());out.add(dto(shares.save(s)));audit.record(sender,d,"SHARE","Shared with "+receiver.getEmail());}return out;}
 @Transactional(readOnly=true) public List<ShareResponse> sharedWithMe(){return shares.findBySharedToOrderBySharedAtDesc(current()).stream().map(this::dto).toList();}
 private User current(){return users.findByEmail(SecurityContextHolder.getContext().getAuthentication().getName()).orElseThrow(()->new ResourceNotFoundException("User not found"));} private ShareResponse dto(DocumentShare s){return new ShareResponse(s.getId(),s.getDocument().getId(),s.getDocument().getFileName(),s.getSharedBy().getFullName(),s.getSharedAt(),s.getPermission());}
}
